// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const adminSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  userId: z.union([z.string(), objectIdSchema]),
  email: z.string(),
  adminRoleTemplateId: z.union([z.string(), objectIdSchema]),
  customPermissions: z.array(
    z.object({
      permission: z.union([z.string(), objectIdSchema]),
      granted: z.boolean(),
      resources: z.array(z.string()),
    }),
  ),
  scope: z
    .object({
      businessIds: z.union([z.array(z.string()), z.array(objectIdSchema)]),
      features: z.array(z.string()),
    })
    .optional(),
  addedBy: z.union([z.string(), objectIdSchema]),
  status: z.string(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
