// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const adminPermissionSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  name: z.string(),
  description: z.string(),
  resource: z.string(),
  action: z.string(),
  category: z.string(),
  implications: z.array(z.string()),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
