// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const adminRoleTemplateSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  name: z.string(),
  description: z.string(),
  basePermissions: z.array(z.string()),
  hierarchy: z.object({
    level: z.number(),
    canManageRoles: z.array(z.string()),
  }),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
