// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const authProviderSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  /**
   * Auth provider name (e.g., "clerk")
   * @minLength 1 Provider name is required
   */
  provider: z.string().min(1, 'Provider name is required'),
  isActive: z.boolean(),
  metadataMap: z.object({
    userId: z.string(),
    email: z.string(),
    name: z.string(),
    roles: z.string(),
  }),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
