// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const businessSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  name: z.string(),
  slug: z.string(),
  domains: z.array(z.string()),
  settings: z.object({
    defaultRoleId: z.union([z.string(), objectIdSchema]).optional(),
    invitationExpiry: z.number(),
    enforceHierarchy: z.boolean(),
    permissionPolicy: z.string(),
  }),
  setup: z.object({
    status: z.string().optional(),
    completedSteps: z.array(z.string()).optional(),
    createdBy: z.union([z.string(), objectIdSchema]).optional(),
    ownerInvitationId: z.union([z.string(), objectIdSchema]).optional(),
  }),
  updatedBy: z.union([z.string(), objectIdSchema]).optional(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
