// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const businessSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  /**
   * Business name
   * @minLength 1 Name is required
   */
  name: z.string().min(1, 'Name is required'),
  /**
   * Business slug - must contain only alphanumeric characters and underscores
   * @pattern ^[a-zA-Z0-9_]+$
   */
  slug: z.string().regex(/^[a-zA-Z0-9_]+$/),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
