// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const contractSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  url: z.string(),
  gsBucketName: z.string().optional(),
  fileName: z.string(),
  contractTypeId: z.union([z.string(), objectIdSchema]).optional(),
  summary: z.string().optional(),
  terms: z.array(z.record(z.string())).optional(),
  businessId: z.union([z.string(), objectIdSchema]),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
  createdBy: z.string().optional(),
  updatedBy: z.string().optional(),
});
