// Generated by ts-to-zod
import { z } from 'zod';

export const contractKeyTermDefinitionSchema = z.object({
  term: z.string(),
  description: z.string(),
  outputFormat: z.string(),
  sampleOutput: z.array(z.string()),
});

const objectIdSchema = z.any();

export const contractTypeSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  shortName: z.string(),
  longName: z.string(),
  description: z.string().optional(),
  keyTerms: z.array(contractKeyTermDefinitionSchema),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
