// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

const clauseDefinitionSchema = z.any();

export const contractTypeSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  shortName: z.string(),
  longName: z.string(),
  description: z.string().optional(),
  /**
   * The **standard** clauses that are applicable to the contract type, set during initialization
   * ONLY for standard clauses (i.e., clauses that have isCustom set to false or undefined)
   */
  clauses: z.union([z.array(z.string()), z.array(objectIdSchema)]),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});

export const contractTypePopulatedSchema = contractTypeSchema
  .omit({ clauses: true })
  .extend({
    clauses: z.array(clauseDefinitionSchema),
  });
