// Generated by ts-to-zod
import { z } from 'zod';

import { ContractStatus } from '../../models/interfaces/contract';

export const contractStatusSchema = z.nativeEnum(ContractStatus);

const objectIdSchema = z.any();

const clauseSchema = z.any();

export const partySchema = z.object({
  _id: z.union([z.string(), objectIdSchema]).nullable(),
  name: z.string(),
});

export const contractSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  url: z.string(),
  gsBucketName: z.string().optional(),
  parties: z.array(partySchema),
  text: z.string().optional(),
  fileName: z.string(),
  contractTypeId: z.union([z.string(), objectIdSchema]).optional(),
  summary: z.string().optional(),
  label: z.string(),
  clauses: z.record(clauseSchema).optional(),
  businessId: z.union([z.string(), objectIdSchema]),
  tags: z.array(z.string()),
  status: contractStatusSchema,
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
  createdBy: z.string().optional(),
  updatedBy: z.string().optional(),
});
