// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

const clauseSchema = z.any();

export const contractTypeSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  shortName: z.string(),
  longName: z.string(),
  description: z.string().optional(),
  /**
   * The clauses that are applicable to the contract type. References the ids of the clauses.
   * Previously "keyTerms"
   */
  clauses: z.union([z.array(z.string()), z.array(objectIdSchema)]),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});

export const contractTypePopulatedSchema = contractTypeSchema
  .omit({ clauses: true })
  .extend({
    clauses: z.array(clauseSchema),
  });
