// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const partySchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  /**
   * Party name
   * @minLength 1 Name is required
   */
  name: z.string().min(1, 'Name is required'),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
  createdBy: z.string().optional(),
  updatedBy: z.string().optional(),
});
