// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const projectAccessSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  projectId: z.union([z.string(), objectIdSchema]),
  userId: z.union([z.string(), objectIdSchema]),
  businessId: z.union([z.string(), objectIdSchema]),
  accessTypes: z.array(z.string()),
  inherited: z.boolean(),
  source: z.object({
    grantedBy: z.union([z.string(), objectIdSchema]),
    grantedAt: z.date().optional(),
    reasonCode: z.string().optional(),
    comment: z.string().optional(),
  }),
  constraints: z
    .object({
      expiresAt: z.date().optional(),
      conditions: z.record(z.unknown()).optional(),
    })
    .optional(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
