// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const projectSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  /**
   * Project name
   * @minLength 1 Name is required
   */
  name: z.string().min(1, 'Name is required'),
  /**
   * User IDs
   */
  userIds: z.union([z.array(z.string()), z.array(objectIdSchema)]),
  /**
   * Contract IDs
   */
  contractIds: z.union([z.array(z.string()), z.array(objectIdSchema)]),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
  createdBy: z.string().optional(),
  updatedBy: z.string().optional(),
});
