// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const projectAccessSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  projectId: z.union([z.string(), objectIdSchema]),
  userId: z.union([z.string(), objectIdSchema]),
  businessId: z.union([z.string(), objectIdSchema]),
  /**
   * Array of access types ("view", "edit", "admin")
   */
  accessTypes: z.array(z.string()),
  /**
   * Whether access was inherited from role
   */
  inherited: z.boolean(),
  source: z.object({
    /**
     * Who granted this access
     */
    grantedBy: z.union([z.string(), objectIdSchema]),
    /**
     * When access was granted
     */
    grantedAt: z.date().optional(),
    /**
     * Optional reason for access grant
     */
    reasonCode: z.string().optional(),
    /**
     * Optional explanation
     */
    comment: z.string().optional(),
  }),
  constraints: z
    .object({
      /**
       * Optional access expiration
       */
      expiresAt: z.date().optional(),
      /**
       * Custom conditional restrictions
       */
      conditions: z.record(z.unknown()).optional(),
    })
    .optional(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
