// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const projectSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  name: z.string(),
  client: z.string(),
  businessId: z.union([z.string(), objectIdSchema]),
  type: z.string(),
  status: z.string(),
  metadata: z.object({
    region: z.string().optional(),
    department: z.string().optional(),
    priority: z.number().optional(),
    tags: z.array(z.string()).optional(),
  }),
  ownership: z.object({
    primaryOwnerId: z.union([z.string(), objectIdSchema]),
    secondaryOwnerIds: z
      .array(z.union([z.string(), objectIdSchema]))
      .optional(),
  }),
  dates: z.object({
    created: z.date().optional(),
    updated: z.date().optional(),
    dueDate: z.date().optional(),
    closedDate: z.date().optional(),
  }),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
