// Generated by ts-to-zod
import { z } from 'zod';

export const customPermissionSchema = z.object({
  permission: z.string(),
  granted: z.boolean(),
  resources: z.array(z.string()).optional(),
  conditions: z.record(z.unknown()).optional(),
});

const objectIdSchema = z.any();

export const userRoleSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  userId: z.union([z.string(), objectIdSchema]),
  businessId: z.union([z.string(), objectIdSchema]),
  userRoleTemplateId: z.union([z.string(), objectIdSchema]),
  isActive: z.boolean(),
  scope: z.object({
    isGlobal: z.boolean(),
    projectIds: z.array(z.string()).optional(),
  }),
  customPermissions: z.array(customPermissionSchema).optional(),
  assignedBy: z.union([z.string(), objectIdSchema]),
  assignedAt: z.date().optional(),
  expiresAt: z.date().optional(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
