// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const userPermissionSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  name: z.string(),
  description: z.string(),
  resource: z.string(),
  subResource: z.string().optional(),
  action: z.string(),
  category: z.string(),
  implications: z.array(z.string()).optional(),
  isSystem: z.boolean(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
