// Generated by ts-to-zod
import { z } from 'zod';

import { UserStatus } from '../../models/interfaces/user';

export const userStatusSchema = z.nativeEnum(UserStatus);

export const userProfileSchema = z.object({
  firstName: z.string(),
  lastName: z.string().optional(),
  phone: z.string().optional(),
  image: z.string().optional(),
});

const objectIdSchema = z.any();

export const userSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  email: z.string(),
  role: userStatusSchema,
  profile: userProfileSchema,
  teamIds: z.union([z.array(z.string()), z.array(objectIdSchema)]),
  managedTeamIds: z.union([z.array(z.string()), z.array(objectIdSchema)]),
  viewIds: z.union([z.array(z.string()), z.array(objectIdSchema)]),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
  createdBy: z.string().optional(),
  updatedBy: z.string().optional(),
});
