// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const userPermissionSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  businessId: z.union([z.string(), objectIdSchema]),
  /**
   * Unique identifier (e.g., "contract:approve")
   */
  name: z.string(),
  description: z.string(),
  /**
   * Resource type ("contract", "project", etc.)
   */
  resource: z.string(),
  /**
   * Action ("create", "read", "update", etc.)
   */
  action: z.string(),
  /**
   * Grouping ("legal", "sales", "admin")
   */
  category: z.string(),
  /**
   * Other permissions this includes
   */
  implications: z.array(z.string()).optional(),
  /**
   * System-defined or custom
   */
  isSystem: z.boolean(),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
