// Generated by ts-to-zod
import { z } from 'zod';

const objectIdSchema = z.any();

export const userSchema = z.object({
  id: z.union([z.string(), objectIdSchema]).optional(),
  /**
   * ID from auth provider
   */
  externalId: z.string(),
  /**
   * Primary email address
   * @format email
   */
  email: z.string().email(),
  businessId: z.union([z.string(), objectIdSchema]),
  otherBusinesses: z.array(z.union([z.string(), objectIdSchema])).optional(),
  status: z.string(),
  onboarding: z.object({
    completedAt: z.date().optional(),
    invitationId: z.union([z.string(), objectIdSchema]).optional(),
    isBusinessOwner: z.boolean(),
  }),
  profile: z.object({
    firstName: z.string(),
    lastName: z.string(),
    jobTitle: z.string().optional(),
    department: z.string().optional(),
    region: z.string().optional(),
    timezone: z.string().optional(),
  }),
  hierarchy: z
    .object({
      /**
       * Direct supervisor/manager
       */
      managerId: z.union([z.string(), objectIdSchema]).optional(),
      /**
       * Hierarchy level (lower = higher rank)
       */
      level: z.number().optional(),
      /**
       * Users reporting to this user
       */
      directReports: z.array(z.union([z.string(), objectIdSchema])).optional(),
    })
    .optional(),
  authProvider: z.object({
    provider: z.string(),
    lastLogin: z.date().optional(),
    metadata: z.record(z.unknown()).optional(),
  }),
  createdAt: z.date().optional(),
  updatedAt: z.date().optional(),
});
